package com.rjnsdev.linklift.app.util

import android.content.Context
import android.net.Uri
import java.io.File
import java.io.InputStream
import java.io.OutputStream

/**
 * Manages the local Netscape cookies file (`youtube_cookies.txt`) stored in app-private sandbox.
 */
object CookieHelper {
    const val COOKIE_FILE_NAME = "youtube_cookies.txt"

    val NETSCAPE_HEADER = """
        # Netscape HTTP Cookie File
        # Generated by LinkLift
        # This is a generated file! Do not edit.
        
    """.trimIndent()

    data class CookieEntry(
        val domain: String,
        val path: String = "/",
        val isSecure: Boolean = true,
        val expiry: Long = 2147483647L, // default far-future expiry
        val name: String,
        val value: String,
    ) {
        fun toNetscapeLine(): String {
            val normalizedDomain = if (domain.startsWith(".") || domain.contains(":")) domain else ".$domain"
            val includeSubdomains = if (normalizedDomain.startsWith(".")) "TRUE" else "FALSE"
            val secureFlag = if (isSecure) "TRUE" else "FALSE"
            return "$normalizedDomain\t$includeSubdomains\t$path\t$secureFlag\t$expiry\t$name\t$value"
        }
    }

    fun getCookieFile(context: Context): File =
        File(context.filesDir, COOKIE_FILE_NAME)

    fun getCookieFilePath(context: Context): String? {
        val file = getCookieFile(context)
        return if (file.exists() && file.length() > 0) file.absolutePath else null
    }

    fun hasValidCookies(context: Context): Boolean {
        val file = getCookieFile(context)
        return file.exists() && file.length() > 0
    }

    fun getCookiesLastModified(context: Context): Long {
        val file = getCookieFile(context)
        return if (file.exists()) file.lastModified() else 0L
    }

    fun clearCookies(context: Context): Boolean {
        val file = getCookieFile(context)
        return if (file.exists()) file.delete() else true
    }

    fun formatCookieEntriesToNetscape(entries: List<CookieEntry>): String {
        val sb = StringBuilder(NETSCAPE_HEADER)
        entries.forEach { entry ->
            if (entry.name.isNotBlank()) {
                sb.append(entry.toNetscapeLine()).append("\n")
            }
        }
        return sb.toString()
    }

    /**
     * Converts a raw Cookie string (from `CookieManager.getCookie` e.g. "NAME1=val1; NAME2=val2")
     * into Netscape HTTP Cookie formatted lines.
     */
    fun formatRawCookieStringToNetscape(
        cookieString: String,
        defaultDomain: String = ".youtube.com",
    ): String {
        if (cookieString.isBlank()) return ""
        val entries = mutableListOf<CookieEntry>()
        val pairs = cookieString.split(";")
        for (pair in pairs) {
            val trimmed = pair.trim()
            if (trimmed.isEmpty() || !trimmed.contains("=")) continue
            val parts = trimmed.split("=", limit = 2)
            val name = parts[0].trim()
            val value = if (parts.size > 1) parts[1].trim() else ""
            if (name.isNotEmpty()) {
                entries.add(
                    CookieEntry(
                        domain = defaultDomain,
                        path = "/",
                        isSecure = name.startsWith("__Secure-") || name.startsWith("__Host-") || name == "SAPISID" || name == "SSID",
                        expiry = System.currentTimeMillis() / 1000L + (180L * 24 * 3600), // ~6 months
                        name = name,
                        value = value,
                    )
                )
            }
        }
        return formatCookieEntriesToNetscape(entries)
    }

    /**
     * Imports cookies from text (either Netscape format or raw semicolon-separated key-value pairs).
     */
    fun importFromText(context: Context, text: String): Result<Int> = runCatching {
        val trimmed = text.trim()
        require(trimmed.isNotEmpty()) { "Cookie text is empty" }

        val contentToWrite: String
        val count: Int

        if (trimmed.startsWith("# Netscape HTTP Cookie File") || trimmed.lines().any { it.contains("\t") && !it.startsWith("#") }) {
            // Already in Netscape format
            val validLines = trimmed.lines().filter { it.isNotBlank() && !it.startsWith("#") && it.split("\t").size >= 6 }
            require(validLines.isNotEmpty()) { "No valid Netscape cookie entries found in file" }
            contentToWrite = if (trimmed.startsWith("# Netscape HTTP Cookie File")) {
                trimmed
            } else {
                "$NETSCAPE_HEADER\n$trimmed"
            }
            count = validLines.size
        } else {
            // Raw header format e.g. "SID=...; HSID=..."
            val netscape = formatRawCookieStringToNetscape(trimmed)
            require(netscape.isNotBlank()) { "Could not parse any cookies from text" }
            contentToWrite = netscape
            count = netscape.lines().count { it.isNotBlank() && !it.startsWith("#") }
        }

        val file = getCookieFile(context)
        file.writeText(contentToWrite)
        count
    }

    /**
     * Imports a `cookies.txt` file from a SAF document Uri.
     */
    fun importFromUri(context: Context, uri: Uri): Result<Int> = runCatching {
        val stream: InputStream = context.contentResolver.openInputStream(uri)
            ?: throw IllegalArgumentException("Could not open selected file")
        val content = stream.use { it.bufferedReader().readText() }
        importFromText(context, content).getOrThrow()
    }

    /**
     * Exports current cookies content as text.
     */
    fun exportCookies(context: Context): String? {
        val file = getCookieFile(context)
        return if (file.exists() && file.length() > 0) file.readText() else null
    }

    /**
     * Exports cookies to a user-selected SAF Uri.
     */
    fun exportToUri(context: Context, targetUri: Uri): Result<Unit> = runCatching {
        val content = exportCookies(context)
            ?: throw IllegalStateException("No cookies available to export")
        val out: OutputStream = context.contentResolver.openOutputStream(targetUri)
            ?: throw IllegalArgumentException("Could not open destination file")
        out.use { it.bufferedWriter().write(content) }
    }
}
